SELECT * FROM "DimCustomers";

SELECT * FROM "DimProducts";

SELECT * FROM "FactOrders";

SELECT * FROM "FactOrderItems";

SELECT * FROM "FactPayment";

--1. How many total orders has UrbanCart received so far?

SELECT 
		COUNT(DISTINCT order_id) as Total_orders
FROM "FactOrders"


--2. Which cities generate the highest number of orders & revenue?
-- code 1 [Used this code for data generation]


WITH completed_orders as 
(
		SELECT 
				order_id, customer_id, status
		FROM "FactOrders"
		WHERE
				"status" = 'Completed'
)
,

customer_city_info as
(
		SELECT
				customer_id, city
		FROM "DimCustomers"				
)
,

order_product_info as 
(
		SELECT 
				foi.order_id as order_id,
				foi.quantity as quantity,
				dp.product_id as product_id,
				dp.unit_price as unit_price
		FROM "FactOrderItems" foi
				LEFT JOIN "DimProducts" dp
				ON
				foi.product_id = dp.product_id				
		
)

-- Since there this question is reveneu related therfore, we will only consider completed orders

SELECT	
		cci.city,
		count(DISTINCT co.order_id) total_oders,
		sum(opi.unit_price * opi.quantity) as total_revenue
		
FROM completed_orders co
		LEFT JOIN customer_city_info cci
		ON
		co.customer_id = cci.customer_id
		LEFT JOIN order_product_info as opi
		ON
		co.order_id = opi.order_id

GROUP BY 1
ORDER BY 2 DESC


-- SIMPLIFIED CODE

SELECT 
		city,
		COUNT(DISTINCT fo.order_id),
		SUM(foi.quantity * dp.unit_price)
		
FROM "FactOrders" as fo
INNER JOIN "DimCustomers" as dc
		ON
		fo.customer_id = dc.customer_id
INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id

WHERE
		fo.status = 'Completed'

GROUP BY 1
ORDER BY 2 DESC


--3. What percent of total customers uses gmail?

SELECT 	
		CASE 
			WHEN email LIKE '%gmail.com' THEN 'gmail'
			WHEN email LIKE '%outlook.com' THEN 'outlook'
			WHEN email LIKE '%yahoo' THEN 'yahoo'
			ELSE 'yahoo'
			
		END AS email_provider,
		
		COUNT(DISTINCT customer_id) as total_customers,
		ROUND(COUNT(customer_id)*100.0 / SUM(COUNT(customer_id)) OVER(), 2) AS Percentage
		
		
			
FROM "DimCustomers"

GROUP BY 1
ORDER BY 1 ASC


--4. What is the monthly trend of total orders over time?
-- code 1 [used this one for data generation]

SELECT 
    -- extract year and month
    TO_CHAR(order_date::DATE, 'YYYY-MM') AS order_month, 
    
    --  count unique orders
    COUNT(order_id) AS total_orders
    
FROM "FactOrders"

GROUP BY 1

ORDER BY 1 ASC;

--code 2
SELECT 	
		CASE 
			WHEN EXTRACT(MONTH FROM order_date) = 1 THEN 'jan'
			WHEN EXTRACT(MONTH FROM order_date) = 2 THEN 'feb'
			WHEN EXTRACT(MONTH FROM order_date) = 3 THEN 'mar'
			WHEN EXTRACT(MONTH FROM order_date) = 4 THEN 'apr'
			WHEN EXTRACT(MONTH FROM order_date) = 5 THEN 'may'
			WHEN EXTRACT(MONTH FROM order_date) = 6 THEN 'jun'
			WHEN EXTRACT(MONTH FROM order_date) = 7 THEN 'jul'
			WHEN EXTRACT(MONTH FROM order_date) = 8 THEN 'aug'
			WHEN EXTRACT(MONTH FROM order_date) = 9 THEN 'sep'
			WHEN EXTRACT(MONTH FROM order_date) = 10 THEN 'oct'
			WHEN EXTRACT(MONTH FROM order_date) = 11 THEN 'nov'
			WHEN EXTRACT(MONTH FROM order_date) = 12 THEN 'dec'
		ELSE NULL
		END AS month_name_2025,
		count(order_date) as monthly_orders
					
			
FROM "FactOrders"
GROUP BY 1 
ORDER BY 2 DESC



-- 5. What is the Completed, Pending & Cancelled Rate?

SELECT
		status,
		COUNT(order_id) AS total_orders,
		ROUND(
			(COUNT(order_id * 100.0) / SUM(COUNT(order_id)) OVER()) * 100,
			2
		) AS rate_of_status
FROM "FactOrders"
GROUP BY 1
ORDER BY 3 DESC



--6. What is the total revenue generated by UrbanCart?

SELECT 
		SUM(foi.quantity * dp.unit_price)
		
FROM "FactOrders" as fo

INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id

WHERE
		fo.status = 'Completed'


--7. Which product categories contribute the most to total revenue?

SELECT 	
		
		dp.category,
		SUM(foi.quantity * dp.unit_price) as total_revenue
		
FROM "FactOrders" as fo
INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id
WHERE
		fo.status = 'Completed'
GROUP BY 1
ORDER BY 2 DESC






-- 8. Which individual products generate the highest revenue?

SELECT 	
		dp.product_name,
		dp.category,
		SUM(dp.unit_price * foi.quantity) as total_revenue
		
		
		
FROM "FactOrders" as fo
INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id
WHERE
		fo.status = 'Completed'

GROUP BY 1,2
ORDER BY 3 DESC



-- 9. What is the average order value (AOV) and Average Basket Size?
-- code 1 [used this one for data generation]
WITH completed_combined_table as
(
	SELECT 
			fo.order_id,
			fo.customer_id,
			fo.order_date,
			fo.status,
			foi.order_item_id,
			foi.quantity,
			dp.product_id,
			dp.product_name,
			dp.category,
			dp.unit_price,
			dp.stock
	FROM "FactOrders" as fo
	INNER JOIN "FactOrderItems" as foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" as dp
			ON
			foi.product_id = dp.product_id
	INNER JOIN "DimCustomers" as dc
			ON
			fo.customer_id = dc.customer_id

	WHERE
			fo.status = 'Completed'	

)
SELECT 
		ROUND( SUM(quantity * unit_price)/COUNT(DISTINCT order_id), 2) as avg_order_value,
		ROUND( SUM(quantity)::NUMERIC/COUNT(DISTINCT order_id), 2) as avg_basket_size_items
from completed_combined_table

--code 2

SELECT 
		ROUND( SUM(foi.quantity * dp.unit_price)/COUNT(DISTINCT fo.order_id), 2) as avg_order_value,
		ROUND( SUM(foi.quantity)::NUMERIC/COUNT(DISTINCT fo.order_id), 2) as avg_basket_size_items
FROM "FactOrders" as fo
INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id

WHERE
		fo.status = 'Completed'





-- 10. Which products are at risk of stock-out due to high sales volume and low inventory?


SELECT 
		dp.product_id,
		dp.product_name,
		SUM(foi.quantity) as total_sold,
		ROUND(dp.stock - SUM(foi.quantity), 2)as available_stock,
		dp.stock AS initial_stock
		
FROM "FactOrders" as fo
INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id

WHERE
		fo.status = 'Completed'

GROUP BY  1,2, dp.stock
ORDER BY 4 ASC, 3 DESC



-- 11. Which customers contribute the highest total revenue?


--CODE: 1 [used this one for data generation]


SELECT
		dc.customer_id,
		dc.full_name,
		dc.email,
		dc.phone,
		dc.city,
		SUM(dp.unit_price*foi.quantity) AS total_revenue

		
FROM "FactOrders" AS fo
	INNER JOIN "FactOrderItems" AS foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" AS dp
			ON
			foi.product_id = dp.product_id
	INNER JOIN "DimCustomers" AS dc
			ON
			fo.customer_id = dc.customer_id
	WHERE
			fo.status = 'Completed'

GROUP BY 1,2,3,4,5
ORDER BY 6 DESC

--CODE: 2

WITH completed_combined_table AS
(
	SELECT 
			fo.customer_id AS customer_id,
			fo.order_id AS order_id,			
			fo.order_date AS order_date,
			fo.status AS status,
			dc.full_name AS full_name,
			dc.gender AS gender,
			dc.email AS email,
			dc.city AS city,
			dc.phone AS phone,
			foi.order_item_id AS order_item_id,
			foi.quantity AS quantity,
			dp.product_id AS product_id,
			dp.product_name AS product_name,
			dp.category AS category,
			dp.unit_price as unit_price,
			dp.stock AS stock
	FROM "FactOrders" AS fo
	INNER JOIN "FactOrderItems" AS foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" AS dp
			ON
			foi.product_id = dp.product_id
	INNER JOIN "DimCustomers" AS dc
			ON
			fo.customer_id = dc.customer_id

	WHERE
			fo.status = 'Completed'
	

)

SELECT 
		customer_id,
		full_name,
		email,
		phone,
		city,
		SUM(unit_price*quantity) AS total_revenue		
		
FROM completed_combined_table

GROUP BY 1,2,3,4,5
ORDER BY 6 DESC




-- 12. Generate a list of cancellation rate by city; also the cancellation rate for customers.


SELECT
		dc.city,
		COUNT(DISTINCT fo.order_id) as total_orders,
		SUM(
			CASE
				WHEN fo.status = 'Cancelled' THEN 1 ELSE 0 END
		)
		AS cancellation_count,
		ROUND(
			SUM(
				CASE WHEN fo.status = 'Cancelled' THEN 1 ELSE 0 END) * 100.0
				/
				COUNT(DISTINCT fo.order_id)
		, 2) AS cancellation_rate
FROM "FactOrders" as fo
		INNER JOIN "DimCustomers" as dc
		ON
		fo.customer_id = dc.customer_id

GROUP BY 1
ORDER BY 2 DESC, 4 DESC


-- 13.Do male and female customers show different purchasing patterns by category?


	
SELECT 		
		dp.category,
		dc.gender,
		COUNT(DISTINCT fo.order_id) AS completed_orders,
		
		SUM(foi.quantity) AS order_quantity,
		SUM(dp.unit_price * foi.quantity) AS total_revenue
		
		
FROM "FactOrders" AS fo
		INNER JOIN "DimCustomers" AS dc
		ON
		fo.customer_id = dc.customer_id
		INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
		INNER JOIN "DimProducts" AS dp
		ON
		foi.product_id = dp.product_id

WHERE fo.status = 'Completed'

GROUP BY 1,2
ORDER BY 1,2,3

-- mored detailed answer

WITH category_gender AS
(
	SELECT
			dp.category,
			dc.gender,
			COUNT(DISTINCT fo.order_id) AS completed_orders,
			COUNT(DISTINCT dc.customer_id) AS unique_customers,
			SUM(foi.quantity) AS order_quantity,
			SUM(dp.unit_price * foi.quantity) as total_revenue

	FROM "FactOrders" AS fo
	INNER JOIN "DimCustomers" AS dc
			ON
			fo.customer_id = dc.customer_id
	INNER JOIN "FactOrderItems" AS foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" AS dp
			ON
			foi.product_id = dp.product_id

	WHERE
			fo.status = 'Completed'
	GROUP BY 1, 2	

)
,
gender_total AS
(
	SELECT
			gender,
			SUM(order_quantity) AS gender_total_quantity,
			SUM(total_revenue) AS gender_total_revenue
	FROM category_gender
	GROUP BY 1
)

SELECT
		cg.category,
		cg.gender,
		cg.completed_orders,
		cg.unique_customers,
		cg.order_quantity,
		cg.total_revenue,
		ROUND(100.0 * cg.order_quantity / gt.gender_total_quantity , 2) AS qty_percent_in_gender,
		ROUND(100.0 * cg.total_revenue / gt.gender_total_revenue , 2) AS rev_percent_in_gender
FROM category_gender AS cg
INNER JOIN gender_total AS gt
		ON
		cg.gender=gt.gender

ORDER BY 2, 8 DESC

-- 14. How does customer purchasing behavior change over time since account creation?

-- without null created at values

WITH order_summary AS (
    SELECT
        fo.order_id,
        fo.customer_id,
        fo.order_date::date AS order_date,
        SUM(foi.quantity) AS total_units,
        SUM(foi.quantity * dp.unit_price) AS gross_sales_proxy
    FROM "FactOrders" fo
    INNER JOIN "FactOrderItems" foi
        ON fo.order_id = foi.order_id
    INNER JOIN "DimProducts" dp
        ON foi.product_id = dp.product_id
    WHERE fo.status = 'Completed'
    GROUP BY
        fo.order_id,
        fo.customer_id,
        fo.order_date
),

customer_order_tenure AS (
    SELECT
        os.order_id,
        os.customer_id,
        os.total_units,
        os.gross_sales_proxy,
        os.order_date - dc.created_at::date AS days_since_account_creation
    FROM order_summary os
    INNER JOIN "DimCustomers" dc
        ON os.customer_id = dc.customer_id
    WHERE dc.created_at IS NOT NULL
      AND os.order_date >= dc.created_at::date
),

tenure_buckets AS (
    SELECT
        *,
        CASE
            WHEN days_since_account_creation BETWEEN 0 AND 30
                THEN '0-30 days'
            WHEN days_since_account_creation BETWEEN 31 AND 60
                THEN '31-60 days'
            WHEN days_since_account_creation BETWEEN 61 AND 90
                THEN '61-90 days'
            ELSE '91+ days'
        END AS account_age_bucket,

        CASE
            WHEN days_since_account_creation BETWEEN 0 AND 30 THEN 1
            WHEN days_since_account_creation BETWEEN 31 AND 60 THEN 2
            WHEN days_since_account_creation BETWEEN 61 AND 90 THEN 3
            ELSE 4
        END AS bucket_order
    FROM customer_order_tenure
)

SELECT
    account_age_bucket,
    COUNT(DISTINCT customer_id) AS active_customers,
    COUNT(DISTINCT order_id) AS completed_orders,
    ROUND(
        COUNT(DISTINCT order_id)::numeric
        / COUNT(DISTINCT customer_id),
        2
    ) AS orders_per_active_customer,
    ROUND(AVG(total_units), 2) AS avg_units_per_order,
    ROUND(AVG(gross_sales_proxy), 2) AS avg_order_value_proxy,
    ROUND(SUM(gross_sales_proxy), 2) AS gross_sales_proxy
FROM tenure_buckets
GROUP BY
    account_age_bucket,
    bucket_order
ORDER BY
    bucket_order;

-- with null created_at values
WITH earliest_order_date AS (
	-- with this cte we find out earliest order date
    SELECT MIN(order_date::date) AS min_order_date
    FROM "FactOrders"
),

clean_customers AS (
	-- some customer may not have a id creation date but they ordered from the shop
	-- in this table we have taken the earliest order date as id_creation date
	-- for the rows we do not have a value for created_at
    SELECT 
        customer_id,
        COALESCE(created_at::date, eod.min_order_date) AS account_created_date
    FROM "DimCustomers", earliest_order_date eod
),

order_summary AS (
    SELECT
        fo.order_id,
        fo.customer_id,
        fo.order_date::date AS order_date,
        SUM(foi.quantity) AS total_units,
        SUM(foi.quantity * dp.unit_price) AS gross_sales_proxy
    FROM "FactOrders" fo
    INNER JOIN "FactOrderItems" foi
        ON fo.order_id = foi.order_id
    INNER JOIN "DimProducts" dp
        ON foi.product_id = dp.product_id
    WHERE fo.status = 'Completed'
    GROUP BY
        fo.order_id,
        fo.customer_id,
        fo.order_date
),

customer_order_tenure AS (
    SELECT
        os.order_id,
        os.customer_id,
        os.total_units,
        os.gross_sales_proxy,
        os.order_date - cc.account_created_date AS days_since_account_creation
    FROM order_summary os
    INNER JOIN clean_customers cc
        ON os.customer_id = cc.customer_id
),

tenure_buckets AS (
    SELECT
        *,
        CASE
            WHEN days_since_account_creation BETWEEN 0 AND 30
                THEN '0-30 days'
            WHEN days_since_account_creation BETWEEN 31 AND 60
                THEN '31-60 days'
            WHEN days_since_account_creation BETWEEN 61 AND 90
                THEN '61-90 days'
            ELSE '91+ days'
        END AS account_age_bucket,
        CASE
            WHEN days_since_account_creation BETWEEN 0 AND 30 THEN 1
            WHEN days_since_account_creation BETWEEN 31 AND 60 THEN 2
            WHEN days_since_account_creation BETWEEN 61 AND 90 THEN 3
            ELSE 4
        END AS bucket_order
    FROM customer_order_tenure
)

SELECT
    account_age_bucket,
    COUNT(DISTINCT customer_id) AS active_customers,
    COUNT(DISTINCT order_id) AS completed_orders,
    ROUND(
        COUNT(DISTINCT order_id)::numeric
        / COUNT(DISTINCT customer_id),
        2
    ) AS orders_per_active_customer,
    ROUND(AVG(total_units), 2) AS avg_units_per_order,
    ROUND(AVG(gross_sales_proxy), 2) AS avg_order_value_proxy,
    ROUND(SUM(gross_sales_proxy), 2) AS gross_sales_proxy
FROM tenure_buckets
GROUP BY
    account_age_bucket,
    bucket_order
ORDER BY
    bucket_order;



WITH updated_customer_table
(
	SELECT 
			dc.customer_id,
			COALESCE(dc.created_at, MIN(fo.order_date)) as revised_creation_date
	FROM "FactOrders" fo
	INNER JOIN "DimCustomers" dc
			ON
			fo.customer_id = dc.customer_id
	GROUP BY 1, dc.created_at
)
		
FROM "FactOrders" fo
INNER JOIN "DimCustomers" dc
		ON
		fo.customer_id = dc.customer_id
WHERE dc.created_at IS NULL

-- 15. Generate a list of customers who ordered in October but didn’t order in December.

WITH october_customers AS
(
	SELECT
			DISTINCT customer_id
	FROM "FactOrders"
	WHERE
		order_date::date >= '2025-10-01'
		AND
		order_date::date < '2025-11-01'
)
,

december_customers AS
(
	SELECT
			DISTINCT customer_id
	FROM "FactOrders"
	WHERE
		order_date::date >= '2025-12-01'
		AND
		order_date::date < '2026-01-01'
)

SELECT 	
		oc.customer_id AS customer_id,
		dc.full_name,
		dc.email,
		dc.phone,
		dc.city
FROM october_customers AS oc
LEFT JOIN december_customers AS decc
		ON
		oc.customer_id = decc.customer_id
INNER JOIN "DimCustomers" AS dc
		ON
		oc.customer_id = dc.customer_id
WHERE
	decc."customer_id" IS NULL



-- 16. Generate a list of customers who ordered both in October & December.

WITH october_customers AS
(
	SELECT
			DISTINCT customer_id
	FROM "FactOrders"
	WHERE
		order_date::date >= '2025-10-01'
		AND
		order_date::date < '2025-11-01'
)
,

december_customers AS
(
	SELECT
			DISTINCT customer_id
	FROM "FactOrders"
	WHERE
		order_date::date >= '2025-12-01'
		AND
		order_date::date < '2026-01-01'
)
SELECT 	
		oc.customer_id AS customer_id,
		dc.full_name,
		dc.email,
		dc.phone,
		dc.city
FROM october_customers AS oc
INNER JOIN december_customers AS decc
		ON
		oc.customer_id = decc.customer_id
INNER JOIN "DimCustomers" AS dc
		ON
		oc.customer_id = dc.customer_id


-- 17. Which payment methods are used most frequently?

SELECT
		"FactPayment".method AS pay_method,
		COUNT(DISTINCT payment_id),
		ROUND(100 * COUNT(*) / SUM(COUNT(*)) OVER() , 2) AS rate_of_usage
		
FROM "FactPayment"
GROUP BY 1
ORDER BY 2 DESC

-- if there is a condition for order to be completed
SELECT 
		fp.method,
		COUNT(DISTINCT fo.order_id),
		ROUND(100 * COUNT(*) / SUM(COUNT(*)) OVER() , 2) AS rate_of_usage
		
FROM "FactOrders" fo
INNER JOIN "FactPayment" fp
		ON
		fo.order_id = fp.order_id
WHERE
		status = 'Completed'
GROUP BY 1
ORDER BY 2 DESC

-- 18. Is there any relationship between payment method and order status?
WITH method_status_count AS
(	
	SELECT 
			fp.method AS pay_method,
			fo.status AS order_status,
			COUNT(DISTINCT fo.order_id) AS no_of_orders
	FROM "FactOrders" fo
	INNER JOIN "FactPayment" fp
			ON
			fo.order_id = fp.order_id
	GROUP BY 1, 2
	
)


SELECT 	
		pay_method,
		order_status,
		no_of_orders,
		ROUND(
			no_of_orders * 100.0 / SUM(no_of_orders) OVER (PARTITION BY pay_method), 2
		) AS rate_of_status	
FROM method_status_count

ORDER BY 1, 2 , 3 DESC

-- 19.Do certain cities prefer specific payment methods?

WITH method_city_table AS 
(
	SELECT
			dc.city,
			fp.method AS pay_method,
			COUNT(DISTINCT fo.order_id) AS count_orders
			
			
	FROM "FactOrders" AS fo
	INNER JOIN "DimCustomers" AS dc
			ON
			fo.customer_id = dc.customer_id
	INNER JOIN "FactPayment" AS fp
			ON
			fo.order_id = fp.order_id
	
	GROUP BY 1, 2
	
)

SELECT	
		city,
		pay_method,
		count_orders,
		ROUND(count_orders *100.0 / SUM(count_orders) OVER (PARTITION BY city), 2) AS city_method_percentage

FROM method_city_table

ORDER BY 1, 4 DESC



--

-- 20. Are higher-value orders associated with specific payment methods?

-- only the avg order value
WITH order_value AS 

(
	SELECT 
			fo.order_id,
			fp.method AS pay_method,
			SUM(foi.quantity * dp.unit_price) AS total_order_value
	FROM "FactOrders" fo
	INNER JOIN "FactOrderItems" foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" dp
			ON
			foi.product_id = dp.product_id
	INNER JOIN "FactPayment" fp
			ON
			fo.order_id = fp.order_id
	WHERE fo.status = 'Completed'
	
	GROUP BY fo.order_id, fp.method
)

SELECT
		pay_method,
		COUNT(order_id) AS order_count,
		ROUND(AVG(total_order_value), 2) AS avg_order_value
FROM order_value
GROUP BY pay_method
ORDER BY avg_order_value DESC

-- detailed data
WITH order_value AS
(
	SELECT
			fo.order_id,
			fp.method as pay_method,
			SUM(foi.quantity * dp.unit_price) AS order_value
	FROM "FactOrders" fo
	INNER JOIN "FactOrderItems" foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" dp
        ON foi.product_id = dp.product_id
    INNER JOIN "FactPayment" fp
        ON fo.order_id = fp.order_id
    WHERE fo.status = 'Completed'
    GROUP BY 1 , 2
)
SELECT 
		pay_method,
		COUNT(order_id) AS completed_orders,
		ROUND(AVG(order_value), 2) AS average_order_value,
		ROUND(SUM(order_value), 2) AS gross_sale_current,
		ROUND(MIN(order_value), 2) AS lowest_order_value,
		ROUND(MAX(order_value), 2) AS highest_order_value

FROM order_value
GROUP BY 1
ORDER BY 3 DESC

-- 21. What is the average number of items per order by payment method?


WITH item_order_summary AS(
	SELECT 
			fp.method AS pay_method,
			foi.order_id,
			COUNT(foi.order_item_id) AS product_count,
			SUM(foi.quantity) AS total_units

	FROM "FactOrderItems" foi
	INNER JOIN "FactPayment" fp
			ON
			foi.order_id = fp.order_id
	GROUP BY 1, 2
)

SELECT 
		pay_method,
		COUNT(order_id) AS total_orders,
		ROUND(AVG(product_count), 2) AS avg_product_count_per_order,
		ROUND(AVG(total_units), 2) AS avg_unit_per_order
FROM item_order_summary
GROUP BY 1
ORDER BY 4 DESC

--

SELECT * FROM "DimProducts"

SELECT
		category,
		SUM(unit_price) AS total_price_per_category,
		ROUND(
			SUM(unit_price) / COUNT(unit_price), 2
		) AS avg_price_for_category
FROM "DimProducts"
GROUP BY 1
ORDER BY 3 DESC

SELECT
		category,
		SUM(unit_price) AS total_price_per_category,
		ROUND(
			AVG(unit_price), 2
		) AS avg_price_for_category
FROM "DimProducts"
GROUP BY 1
ORDER BY 3 DESC


-- 22.Create a list to show the difference between the category average price and product’s price for all the products.

SELECT
		product_id,
		product_name,
		category,
		unit_price,
		ROUND(AVG(unit_price) OVER(PARTITION BY category) , 2) AS category_avg,
		ROUND(unit_price - AVG(unit_price) OVER(PARTITION BY category) , 2) AS price_diff

FROM "DimProducts"

ORDER BY 5 ASC


-- 23. Which product pairs are most frequently purchased together in the same order?

-- without completed orders

WITH top_paired_products AS
(
	SELECT
			foi1.product_id AS product_id_1,
			foi2.product_id AS product_id_2,
			COUNT(*) AS times_ordered_together
			
	FROM "FactOrderItems" foi1
	JOIN "FactOrderItems" foi2
			ON
			(
			foi1.order_id = foi2.order_id
			AND
			foi1.product_id < foi2.product_id
			)
	GROUP BY 1, 2
	ORDER BY 3 DESC
)
SELECT 
		product_id_1,
		dp1.product_name AS product_1,
		product_id_2,
		dp2.product_name AS product_2,
		times_ordered_together
FROM top_paired_products top_pair
LEFT JOIN "DimProducts" dp1
		ON 
		top_pair.product_id_1 = dp1.product_id
LEFT JOIN "DimProducts" dp2
		ON
		top_pair.product_id_2 = dp2.product_id

ORDER BY 5 DESC


-- with completed orders

WITH top_paired_products AS
(
	SELECT
			foi1.product_id AS product_id_1,
			foi2.product_id AS product_id_2,
			COUNT(*) AS times_ordered_together
			
	FROM "FactOrderItems" foi1
	JOIN "FactOrderItems" foi2
			ON
			(
			foi1.order_id = foi2.order_id
			AND
			foi1.product_id < foi2.product_id
			)
	INNER JOIN "FactOrders" fo1
			ON
			foi1.order_id = fo1.order_id	
	WHERE fo1.status = 'Completed'
	GROUP BY 1, 2
	ORDER BY 3 DESC
)
SELECT 
		product_id_1,
		dp1.product_name AS product_1,
		product_id_2,
		dp2.product_name AS product_2,
		times_ordered_together
FROM top_paired_products top_pair
LEFT JOIN "DimProducts" dp1
		ON 
		top_pair.product_id_1 = dp1.product_id
LEFT JOIN "DimProducts" dp2
		ON
		top_pair.product_id_2 = dp2.product_id
ORDER BY 5 DESC



-- 24. Which product pairs generate the highest total revenue when sold together?

WITH pair_revenue_summary AS
(
	SELECT
			foi1.product_id AS product_id_1,
			foi2.product_id AS product_id_2,			
			COUNT(*) AS times_ordered_together,
			SUM(
			(foi1.quantity * dp1.unit_price) + (foi2.quantity * dp2.unit_price)
			) AS total_revenue
			
	FROM "FactOrderItems" foi1
	JOIN "FactOrderItems" foi2
			ON
			(
			foi1.order_id = foi2.order_id
			AND
			foi1.product_id < foi2.product_id
			)
	INNER JOIN "FactOrders" fo1
			ON
			foi1.order_id = fo1.order_id	
	JOIN "DimProducts" dp1
			ON
			foi1.product_id = dp1.product_id
	JOIN "DimProducts" dp2
			ON
			foi2.product_id = dp2.product_id
	WHERE fo1.status = 'Completed'
	GROUP BY foi1.product_id, foi2.product_id
	
)
SELECT 
		product_id_1,
		dp1.product_name AS product_1,
		product_id_2,
		dp2.product_name AS product_2,
		prs.times_ordered_together,
		prs.total_revenue
		
FROM pair_revenue_summary prs
LEFT JOIN "DimProducts" dp1
		ON 
		prs.product_id_1 = dp1.product_id
LEFT JOIN "DimProducts" dp2
		ON
		prs.product_id_2 = dp2.product_id

ORDER BY prs.total_revenue DESC

-- 25. Generate a daily report containing the columns Date, Total Orders, Total Items, Completed Orders, Cancelled Orders, Total Revenue

WITH order_items_summary AS (
    SELECT
        fo.order_id,
        fo.order_date::date AS order_date,
        fo.status,
        SUM(foi.quantity) AS total_items,
        SUM(foi.quantity * dp.unit_price) AS order_revenue
    FROM "FactOrders" fo
    INNER JOIN "FactOrderItems" foi
        ON fo.order_id = foi.order_id
    INNER JOIN "DimProducts" dp
        ON foi.product_id = dp.product_id
    GROUP BY fo.order_id, fo.order_date, fo.status
)

SELECT
    order_date AS date,
    COUNT(order_id) AS total_orders,
    SUM(total_items) AS total_items,
    COUNT(CASE WHEN status = 'Completed' THEN 1 END) AS completed_orders,
    COUNT(CASE WHEN status = 'Cancelled' THEN 1 END) AS cancelled_orders,
    ROUND(SUM(CASE WHEN status = 'Completed' THEN order_revenue ELSE 0 END), 2) AS total_revenue
FROM order_items_summary
GROUP BY 1
ORDER BY 1;













