SELECT * FROM "DimCustomers";

SELECT * FROM "DimProducts";

SELECT * FROM "FactOrders";

SELECT * FROM "FactOrderItems";

SELECT * FROM "FactPayment";

--1. How many total orders has UrbanCart received so far?

SELECT 
		COUNT(DISTINCT order_id) as Total_orders
FROM "FactOrders"


--2. Which cities generate the highest number of orders & revenue?

-- checking order table
SELECT * FROM "FactOrders";
SELECT FROM "DimCustomers";


WITH completed_orders as 
(
		SELECT 
				order_id, customer_id, status
		FROM "FactOrders"
		WHERE
				"status" = 'Completed'
)
,

customer_city_info as
(
		SELECT
				customer_id, city
		FROM "DimCustomers"				
)
,

order_product_info as 
(
		SELECT 
				foi.order_id as order_id,
				foi.quantity as quantity,
				dp.product_id as product_id,
				dp.unit_price as unit_price
		FROM "FactOrderItems" foi
				LEFT JOIN "DimProducts" dp
				ON
				foi.product_id = dp.product_id
				
		
)

-- Since there this question is reveneu related therfore, we will only consider completed orders

SELECT	
		cci.city,
		count(DISTINCT co.order_id) total_oders,
		sum(opi.unit_price * opi.quantity) as total_revenue
		
FROM completed_orders co
		LEFT JOIN customer_city_info cci
		ON
		co.customer_id = cci.customer_id
		LEFT JOIN order_product_info as opi
		ON
		co.order_id = opi.order_id

GROUP BY 1
ORDER BY 2 DESC


-- SIMPLIFIED CODE

SELECT 
		city,
		COUNT(DISTINCT fo.order_id),
		SUM(foi.quantity * dp.unit_price)
		
FROM "FactOrders" as fo
INNER JOIN "DimCustomers" as dc
		ON
		fo.customer_id = dc.customer_id
INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id

WHERE
		fo.status = 'Completed'

GROUP BY 1
ORDER BY 2 DESC


--3. What percent of total customers uses gmail?

SELECT 	
		CASE 
			WHEN email LIKE '%gmail.com' THEN 'gmail'
			WHEN email LIKE '%outlook.com' THEN 'outlook'
			WHEN email LIKE '%yahoo' THEN 'yahoo'
			ELSE 'yahoo'
			
		END AS email_provider,
		
		COUNT(DISTINCT customer_id) as total_customers,
		ROUND(COUNT(customer_id)*100.0 / SUM(COUNT(customer_id)) OVER(), 2) AS Percentage
		
		
			
FROM "DimCustomers"

GROUP BY 1
ORDER BY 1 ASC


--4. What is the monthly trend of total orders over time?

SELECT 	
		CASE 
			WHEN EXTRACT(MONTH FROM order_date) = 1 THEN 'jan'
			WHEN EXTRACT(MONTH FROM order_date) = 2 THEN 'feb'
			WHEN EXTRACT(MONTH FROM order_date) = 3 THEN 'mar'
			WHEN EXTRACT(MONTH FROM order_date) = 4 THEN 'apr'
			WHEN EXTRACT(MONTH FROM order_date) = 5 THEN 'may'
			WHEN EXTRACT(MONTH FROM order_date) = 6 THEN 'jun'
			WHEN EXTRACT(MONTH FROM order_date) = 7 THEN 'jul'
			WHEN EXTRACT(MONTH FROM order_date) = 8 THEN 'aug'
			WHEN EXTRACT(MONTH FROM order_date) = 9 THEN 'sep'
			WHEN EXTRACT(MONTH FROM order_date) = 10 THEN 'oct'
			WHEN EXTRACT(MONTH FROM order_date) = 11 THEN 'nov'
			WHEN EXTRACT(MONTH FROM order_date) = 12 THEN 'dec'
		ELSE NULL
		END AS month_name,
		count(order_date) as monthly_orders
					
			
FROM "FactOrders"
GROUP BY 1
ORDER BY 1 ASC


SELECT 
    -- Extract just the Year and Month from the full date (e.g., '2025-09')
    TO_CHAR(order_date::DATE, 'YYYY-MM') AS order_month, 
    
    --  Count the number of unique orders
    COUNT(order_id) AS total_orders
    
FROM "FactOrders"

--  Group them by the new month column
GROUP BY 1

--  Sort chronologically from oldest month to newest month
ORDER BY 1 ASC;




--5. What is the total revenue generated by UrbanCart?

SELECT 
		SUM(foi.quantity * dp.unit_price)
		
FROM "FactOrders" as fo

INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id

WHERE
		fo.status = 'Completed'


--6. Which product categories contribute the most to total revenue?

SELECT 	
		
		dp.category,
		SUM(foi.quantity * dp.unit_price) as total_revenue
		
FROM "FactOrders" as fo
INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id
WHERE
		fo.status = 'Completed'
GROUP BY 1
ORDER BY 2 DESC






-- 7. Which individual products generate the highest revenue?

SELECT 	
		dp.product_name,
		dp.category,
		SUM(dp.unit_price * foi.quantity) as total_revenue
		
		
		
FROM "FactOrders" as fo
INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id
WHERE
		fo.status = 'Completed'

GROUP BY 1,2
ORDER BY 3 DESC



-- 8. What is the average order value (AOV) and Average Basket Size?


WITH completed_combined_table as
(
	SELECT 
			fo.order_id,
			fo.customer_id,
			fo.order_date,
			fo.status,
			foi.order_item_id,
			foi.quantity,
			dp.product_id,
			dp.product_name,
			dp.category,
			dp.unit_price,
			dp.stock
	FROM "FactOrders" as fo
	INNER JOIN "FactOrderItems" as foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" as dp
			ON
			foi.product_id = dp.product_id
	INNER JOIN "DimCustomers" as dc
			ON
			fo.customer_id = dc.customer_id

	WHERE
			fo.status = 'Completed'
	

)

SELECT 
		ROUND( SUM(quantity * unit_price)/COUNT(DISTINCT order_id), 2) as AOV,
		ROUND( SUM(quantity)::NUMERIC/COUNT(DISTINCT order_id), 2) as AVBS
from combined_table


SELECT 
		ROUND( SUM(foi.quantity * dp.unit_price)/COUNT(DISTINCT fo.order_id), 2) as AOV,
		ROUND( SUM(foi.quantity)::NUMERIC/COUNT(DISTINCT fo.order_id), 2) as AVBS
FROM "FactOrders" as fo
INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id

WHERE
		fo.status = 'Completed'





-- 9. Which products are at risk of stock-out due to high sales volume and low inventory?


SELECT 
		dp.product_id,
		dp.product_name,
		SUM(foi.quantity) as total_sold,
		dp.stock as available_stock
FROM "FactOrders" as fo
INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
INNER JOIN "DimProducts" as dp
		on
		foi.product_id = dp.product_id

WHERE
		fo.status = 'Completed'

GROUP BY  1,2, 4
ORDER BY 4 ASC, 3 DESC



-- 10. Which customers contribute the highest total revenue?
CODE: 1

WITH completed_combined_table AS
(
	SELECT 
			fo.customer_id AS customer_id,
			fo.order_id AS order_id,			
			fo.order_date AS order_date,
			fo.status AS status,
			dc.full_name AS full_name,
			dc.gender AS gender,
			dc.email AS email,
			dc.city AS city,
			dc.phone AS phone,
			foi.order_item_id AS order_item_id,
			foi.quantity AS quantity,
			dp.product_id AS product_id,
			dp.product_name AS product_name,
			dp.category AS category,
			dp.unit_price as unit_price,
			dp.stock AS stock
	FROM "FactOrders" AS fo
	INNER JOIN "FactOrderItems" AS foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" AS dp
			ON
			foi.product_id = dp.product_id
	INNER JOIN "DimCustomers" AS dc
			ON
			fo.customer_id = dc.customer_id

	WHERE
			fo.status = 'Completed'
	

)

SELECT 
		customer_id,
		full_name,
		email,
		phone,
		city,
		SUM(unit_price*quantity) AS total_revenue		
		
FROM completed_combined_table

GROUP BY 1,2,3,4,5
ORDER BY 6 DESC

CODE: 2


SELECT
		dc.customer_id,
		dc.full_name,
		dc.email,
		dc.phone,
		dc.city,
		SUM(dp.unit_price*foi.quantity) AS total_revenue

		
FROM "FactOrders" AS fo
	INNER JOIN "FactOrderItems" AS foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" AS dp
			ON
			foi.product_id = dp.product_id
	INNER JOIN "DimCustomers" AS dc
			ON
			fo.customer_id = dc.customer_id
	WHERE
			fo.status = 'Completed'

GROUP BY 1,2,3,4,5
ORDER BY 6 DESC




-- 11. Generate a list of cancellation rate by city; also the cancellation rate for customers.


-- code: 1

WITH combined_table AS
(
	SELECT 
			fo.customer_id AS customer_id,
			fo.order_id AS order_id,			
			fo.order_date AS order_date,
			fo.status AS status,
			dc.full_name AS full_name,
			dc.gender AS gender,
			dc.email AS email,
			dc.city AS city,
			dc.phone AS phone,
			foi.order_item_id AS order_item_id,
			foi.quantity AS quantity,
			dp.product_id AS product_id,
			dp.product_name AS product_name,
			dp.category AS category,
			dp.unit_price as unit_price,
			dp.stock AS stock
	FROM "FactOrders" AS fo
	INNER JOIN "FactOrderItems" AS foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" AS dp
			ON
			foi.product_id = dp.product_id
	INNER JOIN "DimCustomers" AS dc
			ON
			fo.customer_id = dc.customer_id	

)

SELECT 
		city,
		COUNT(DISTINCT order_id) as total_orders,
		SUM(
			CASE
				WHEN status = 'Cancelled' THEN 1 ELSE 0 END
		)
		AS cancellation_rate

FROM combined_table
GROUP BY 1
ORDER BY 1 ASC, 2 ASC


-- code: 2
SELECT
		dc.city,
		COUNT(DISTINCT fo.order_id) as total_orders,
		SUM(
			CASE
				WHEN fo.status = 'Cancelled' THEN 1 ELSE 0 END
		)
		AS cancellation_count,
		ROUND(
			SUM(
				CASE WHEN fo.status = 'Cancelled' THEN 1 ELSE 0 END) * 100.0
				/
				COUNT(DISTINCT fo.order_id)
		, 2) AS cancellation_rate
FROM "FactOrders" as fo
		INNER JOIN "DimCustomers" as dc
		ON
		fo.customer_id = dc.customer_id

GROUP BY 1
ORDER BY 4 DESC


-- 13.Do male and female customers show different purchasing patterns by category?


	
SELECT 		
		dp.category,
		dc.gender,
		COUNT(DISTINCT fo.order_id) AS completed_orders,
		
		SUM(foi.quantity) AS order_quantity,
		SUM(dp.unit_price * foi.quantity) AS total_revenue
		
		
FROM "FactOrders" AS fo
		INNER JOIN "DimCustomers" AS dc
		ON
		fo.customer_id = dc.customer_id
		INNER JOIN "FactOrderItems" as foi
		ON
		fo.order_id = foi.order_id
		INNER JOIN "DimProducts" AS dp
		ON
		foi.product_id = dp.product_id

WHERE fo.status = 'Completed'

GROUP BY 1,2
ORDER BY 3 DESC, 4 DESC



WITH category_gender AS
(
	SELECT
			dp.category,
			dc.gender,
			COUNT(DISTINCT fo.order_id) AS completed_orders,
			COUNT(DISTINCT dc.customer_id) AS unique_customers,
			SUM(foi.quantity) AS order_quantity,
			SUM(dp.unit_price * foi.quantity) as total_revenue

	FROM "FactOrders" AS fo
	INNER JOIN "DimCustomers" AS dc
			ON
			fo.customer_id = dc.customer_id
	INNER JOIN "FactOrderItems" AS foi
			ON
			fo.order_id = foi.order_id
	INNER JOIN "DimProducts" AS dp
			ON
			foi.product_id = dp.product_id

	WHERE
			fo.status = 'Completed'
	GROUP BY 1, 2	

)
,
gender_total AS
(
	SELECT
			gender,
			SUM(order_quantity) AS gender_total_quantity,
			SUM(total_revenue) AS gender_total_revenue
	FROM category_gender
	GROUP BY 1
)

SELECT
		cg.category,
		cg.gender,
		cg.completed_orders,
		cg.unique_customers,
		cg.order_quantity,
		cg.total_revenue,
		ROUND(100.0 * cg.order_quantity / gt.gender_total_quantity , 2) AS qty_percent_in_gender,
		ROUND(100.0 * cg.total_revenue / gt.gender_total_revenue , 2) AS rev_percent_in_gender
FROM category_gender AS cg
INNER JOIN gender_total AS gt
		ON
		cg.gender=gt.gender

ORDER BY 2, 8 DESC



-- 15. Generate a list of customers who ordered in October but didn’t order in December.

WITH october_customers AS
(
	SELECT
			DISTINCT customer_id
	FROM "FactOrders"
	WHERE
		order_date::date >= '2025-10-01'
		AND
		order_date::date < '2025-11-01'
)
,

december_customers AS
(
	SELECT
			DISTINCT customer_id
	FROM "FactOrders"
	WHERE
		order_date::date >= '2025-12-01'
		AND
		order_date::date < '2026-01-01'
)

SELECT 	
		oc.customer_id AS customer_id,
		dc.full_name,
		dc.email,
		dc.phone,
		dc.city
FROM october_customers AS oc
LEFT JOIN december_customers AS decc
		ON
		oc.customer_id = decc.customer_id
INNER JOIN "DimCustomers" AS dc
		ON
		oc.customer_id = dc.customer_id
WHERE
	decc."customer_id" IS NULL



-- 16. Generate a list of customers who ordered both in October & December.


SELECT 	
		oc.customer_id AS customer_id,
		dc.full_name,
		dc.email,
		dc.phone,
		dc.city
FROM october_customers AS oc
LEFT JOIN december_customers AS decc
		ON
		oc.customer_id = decc.customer_id
INNER JOIN "DimCustomers" AS dc
		ON
		oc.customer_id = dc.customer_id
WHERE
	decc."customer_id" IS NOT NULL

-- 17. Which payment methods are used most frequently?

SELECT
		"FactPayment".method AS pay_method,
		COUNT(DISTINCT payment_id)
FROM "FactPayment"
GROUP BY 1
ORDER BY 2 DESC

-- if there is a condition for order to be completed
SELECT 
		fp.method,
		COUNT(DISTINCT fo.order_id),
		
		
FROM "FactOrders" fo
INNER JOIN "FactPayment" fp
		ON
		fo.order_id = fp.order_id
WHERE
		status = 'Completed'
GROUP BY 1,3
ORDER BY 2 DESC

-- 18. Is there any relationship between payment method and order status?
WITH method_status_count AS
(	
	SELECT 
			fp.method AS pay_method,
			fo.status AS order_status,
			COUNT(DISTINCT fo.order_id) AS no_of_orders
	FROM "FactOrders" fo
	INNER JOIN "FactPayment" fp
			ON
			fo.order_id = fp.order_id
	GROUP BY 1, 2
	
)


SELECT 	
		pay_method,
		order_status,
		no_of_orders,
		ROUND(
			no_of_orders * 100.0 / SUM(no_of_orders) OVER (PARTITION BY pay_method), 2
		)		
FROM method_status_count

ORDER BY 1, 2 , 3 DESC

-- 19.Do certain cities prefer specific payment methods?

WITH method_city_table AS 
(
	SELECT
			dc.city,
			fp.method AS pay_method,
			COUNT(DISTINCT fo.order_id) AS count_orders
			
			
	FROM "FactOrders" AS fo
	INNER JOIN "DimCustomers" AS dc
			ON
			fo.customer_id = dc.customer_id
	INNER JOIN "FactPayment" AS fp
			ON
			fo.order_id = fp.order_id
	
	GROUP BY 1, 2
	
)

SELECT	
		city,
		pay_method,
		count_orders,
		ROUND(count_orders *100.0 / SUM(count_orders) OVER (PARTITION BY city), 2) AS city_method_percentage

FROM method_city_table

ORDER BY 1, 4 DESC



--